FROM adoptopenjdk:11-jre-hotspot
USER root
WORKDIR /opt/kiap
COPY build/libs/dependencies ./
COPY build/libs/spring-boot-loader ./
COPY build/libs/snapshot-dependencies ./
COPY build/libs/application ./
ENTRYPOINT ["java","org.springframework.boot.loader.JarLauncher"]
